import { Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "remixicon/fonts/remixicon.css";
import { ScroolToTop } from "@/components/ScroolToTop";

const fontPopins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata = {
  title: "Company Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${fontPopins.className} antialiased`} id="hero"
      >
        <ScroolToTop />
        <Navbar className="sticky  z-50"/>
        <div className="container mx-auto px-4">
          {children}
        </div>
        
      </body>
    </html>
  );
}
