import { Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "remixicon/fonts/remixicon.css";

const fontPopins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata = {
  title: "Company Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontPopins.className} antialiased`}
      >
        <Navbar />
        <div className="container mx-auto px-4">
          {children}
        </div>
        
      </body>
    </html>
  );
}
